// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVevOBcUk6XoIj2Cj0hr4UmjV836bl-U',
    appId: '1:842873462908:web:11af4bc7719e097bd269f9',
    messagingSenderId: '842873462908',
    projectId: 'flutter-login-app-e98c9',
    authDomain: 'flutter-login-app-e98c9.firebaseapp.com',
    storageBucket: 'flutter-login-app-e98c9.firebasestorage.app',
    measurementId: 'G-HZL323LRL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZV-J42gtvFMbS9WHZFiFhwvvI6DfLnhU',
    appId: '1:842873462908:android:126d31f4b7322d9dd269f9',
    messagingSenderId: '842873462908',
    projectId: 'flutter-login-app-e98c9',
    storageBucket: 'flutter-login-app-e98c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNZoth7mmGhW2gEbfMFEzwA0vcO33hnzg',
    appId: '1:842873462908:ios:43e427333e2f1c6bd269f9',
    messagingSenderId: '842873462908',
    projectId: 'flutter-login-app-e98c9',
    storageBucket: 'flutter-login-app-e98c9.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNZoth7mmGhW2gEbfMFEzwA0vcO33hnzg',
    appId: '1:842873462908:ios:43e427333e2f1c6bd269f9',
    messagingSenderId: '842873462908',
    projectId: 'flutter-login-app-e98c9',
    storageBucket: 'flutter-login-app-e98c9.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTVevOBcUk6XoIj2Cj0hr4UmjV836bl-U',
    appId: '1:842873462908:web:d12a5d5aac220074d269f9',
    messagingSenderId: '842873462908',
    projectId: 'flutter-login-app-e98c9',
    authDomain: 'flutter-login-app-e98c9.firebaseapp.com',
    storageBucket: 'flutter-login-app-e98c9.firebasestorage.app',
    measurementId: 'G-0W6KXHBKSS',
  );
}
